---
title: "Materiales testados Taller Quibdó"
author: "Zulma M. Cucunubá"
date: "2023-08-02"
output: md_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Materiales de entrenamiento testados Taller Quibdó

Lugar: Quibdó, Chocó

Fecha: Julio 16-29 2023

Número de asistentes: 25

*Perfil de los asistentes:*

-   Funcionarios Secretaría Departamental de Salud de Chocó

-   Funcionarios Secretaría Muncicipal de Salud de Quibdó

-   Profesores y egresados de la UTCH

-   Red de parteras de Chocó

Este repositorio contiene:

### Taller 01. Introducción a R y RStudio

Testado pero aún sin correcciones posterior a la actividad.

### Taller 02. Limpieza de datos

No testado por falta de tiempo. Es un taller muy largo, necesita un
re-ajuste máximo para que sea útil para ell propósito.

### Taller 03. Visualización con ggplot

Testado y parcialmente corregido posterior a la actividad.

### Taller 04. R Markdown

Testado y corregido posterior a la actividad.
