---
title: "Taller Básico de Reportes"
subtitle: "Ejercicio Práctico"
date: '2022-10-25'
output:
  pdf_document: default
  html_document: null
  word_document: default
licenses: CC-BY
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Introducción
En este ejercicio usted aplicará los conocimientos adquiridos en los talleres de programación básica, limpieza de datos epidemiológicos y generación de reportes, mediante el uso de RStudio.

## 2. Objetivo
Realizar un reporte epidemiológico, con el fin de motivar la aplicación de los conocimientos adquiridos a lo largo de los talleres.

## 3. Descripción del ejercicio

-  Conformar grupos de cinco (5) personas.
-  Seleccionar una enfermedad para realizar el reporte.
-  Seleccionar la fuente o base de datos, desde donde se obtendrá la información de la enfermedad.
-  Diseñar el contenido del reporte, tablas, gráficas y demás elementos que se consideren necesarios.
-  Crear un proyecto nuevo en RStudio para el reporte.
-  Realizar la limpieza de los datos de la enfermedad.
-  Desarrollar y generar el reporte.
-  Realizar una presentación del reporte generado en el proyecto de RStudio. Tendrán un tiempo de cinco (5) minutos para realizar la exposición, se recomienda hacerla en Power Point.

## 4. Presentación del reporte
Es este espacio podrá exponer la presentación del reporte desarrollado. Se recomienda incluir una sección donde se contextualice al público sobre la enfermedad seleccionada, la fuente de datos utilizada y las herramientas que facilitaron la generación del reporte. 

Al finalizar la presentación se tendrá un espacio de preguntas y retroalimentación por parte de los moderadores y participantes.

## Sobre este documento

### Asuntos legales

**Licencia**: [CC-BY](https://creativecommons.org/licenses/by/3.0/)
**Copyright**: Geraldine Gómez Millán, 2022